onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top_level/clk
add wave -noupdate /top_level/reset
add wave -noupdate /top_level/Clock_50
add wave -noupdate -divider IF
add wave -noupdate /top_level/IFETCH_INST/PC/wr
add wave -noupdate /top_level/IFETCH_INST/PC/din
add wave -noupdate /top_level/IFETCH_INST/PC/dout
add wave -noupdate /top_level/IFETCH_INST/RA1_INV/dout
add wave -noupdate /top_level/IFETCH_INST/RA1_PC/wr
add wave -noupdate /top_level/IFETCH_INST/RA1_PC/dout
add wave -noupdate /top_level/IFETCH_INST/RA1_IR/dout
add wave -noupdate /top_level/IFETCH_INST/RA2_INV/dout
add wave -noupdate /top_level/IFETCH_INST/RA2_PC/wr
add wave -noupdate /top_level/IFETCH_INST/RA2_PC/dout
add wave -noupdate /top_level/IFETCH_INST/RA2_IR/dout
add wave -noupdate -divider RRF
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_free_vec_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_valid_vec_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_free_vec_Rob_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_free_vec_ID_in
add wave -noupdate -divider ID
add wave -noupdate /top_level/ID_INST/rs_full_in
add wave -noupdate /top_level/ID_INST/lw_r7_resolved
add wave -noupdate /top_level/ID_INST/alu_r7_resolved
add wave -noupdate /top_level/ID_INST/jlr_resolved
add wave -noupdate /top_level/ID_INST/store_retirement_count
add wave -noupdate /top_level/ID_INST/taken_branch_detected
add wave -noupdate /top_level/ID_INST/not_taken_branch_detected
add wave -noupdate /top_level/ID_INST/S0
add wave -noupdate /top_level/ID_INST/S1
add wave -noupdate /top_level/ID_INST/S2
add wave -noupdate /top_level/ID_INST/S3
add wave -noupdate /top_level/ID_INST/twoRRnotFree
add wave -noupdate /top_level/ID_INST/spec_tag_reg_out
add wave -noupdate -divider RS
add wave -noupdate /top_level/RS_RRF_SCHED_INST/inst_scheduled
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_inst_val_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op1_val_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op2_val_out
add wave -noupdate -divider ALU_EX
add wave -noupdate /top_level/ALU_P_INST/rb_pc
add wave -noupdate /top_level/ALU_P_INST/rb_pc
add wave -noupdate /top_level/ALU_P_INST/rb_valid
add wave -noupdate /top_level/ALU_P_INST/alu_p_out
add wave -noupdate /top_level/ALU_P_INST/rrf_tag_out
add wave -noupdate -divider LS_EX
add wave -noupdate /top_level/LS_P_INST/rc_pc
add wave -noupdate /top_level/LS_P_INST/rc_ir
add wave -noupdate /top_level/LS_P_INST/rc_valid
add wave -noupdate /top_level/LS_P_INST/ls_p_data_out
add wave -noupdate /top_level/LS_P_INST/rrf_tag_out
add wave -noupdate -divider ROB
add wave -noupdate /top_level/ROB_INST/tail_ptr
add wave -noupdate /top_level/ROB_INST/tail_ptr_out
add wave -noupdate /top_level/ROB_INST/head_ptr
add wave -noupdate /top_level/ROB_INST/head_ptr_out_plus1
add wave -noupdate -divider EXTRAS
add wave -noupdate /top_level/ALU_P_INST/clk
add wave -noupdate /top_level/ALU_P_INST/reset
add wave -noupdate /top_level/ALU_P_INST/rb_pc
add wave -noupdate /top_level/ALU_P_INST/rb_op1
add wave -noupdate /top_level/ALU_P_INST/rb_op2
add wave -noupdate /top_level/ALU_P_INST/rb_ir
add wave -noupdate /top_level/ALU_P_INST/rb_dest_rrtag
add wave -noupdate /top_level/ALU_P_INST/rb_carrytag
add wave -noupdate /top_level/ALU_P_INST/rb_zerotag
add wave -noupdate /top_level/ALU_P_INST/rb_spectag
add wave -noupdate /top_level/ALU_P_INST/rrf_valid_vect_in
add wave -noupdate /top_level/ALU_P_INST/rb_valid
add wave -noupdate /top_level/ALU_P_INST/rbdestr7
add wave -noupdate /top_level/ALU_P_INST/rb_carry
add wave -noupdate /top_level/ALU_P_INST/rb_carryready
add wave -noupdate /top_level/ALU_P_INST/rb_zero
add wave -noupdate /top_level/ALU_P_INST/rb_zeroready
add wave -noupdate /top_level/ALU_P_INST/alu_p_out
add wave -noupdate /top_level/ALU_P_INST/rrf_tag_out
add wave -noupdate /top_level/ALU_P_INST/rrf_valid_vect_alu_p_out
add wave -noupdate /top_level/ALU_P_INST/alu_p_c
add wave -noupdate /top_level/ALU_P_INST/alu_p_z
add wave -noupdate /top_level/ALU_P_INST/alu_p_brach_taken
add wave -noupdate /top_level/ALU_P_INST/alu_p_brach_nottaken
add wave -noupdate /top_level/ALU_P_INST/jlr_resolved
add wave -noupdate /top_level/ALU_P_INST/alu_r7_resolved
add wave -noupdate /top_level/ALU_P_INST/alu_p_valid_out
add wave -noupdate /top_level/ALU_P_INST/alu_p_rrf_en
add wave -noupdate /top_level/ALU_P_INST/alu_p_no_ans
add wave -noupdate /top_level/ALU_P_INST/alu_p_pc_out
add wave -noupdate /top_level/ALU_P_INST/rb_op2_out
add wave -noupdate /top_level/ALU_P_INST/rb_pcout
add wave -noupdate /top_level/ALU_P_INST/rb_op1out
add wave -noupdate /top_level/ALU_P_INST/rb_op2out
add wave -noupdate /top_level/ALU_P_INST/alu_in_a
add wave -noupdate /top_level/ALU_P_INST/alu_in_b
add wave -noupdate /top_level/ALU_P_INST/alu_add_out
add wave -noupdate /top_level/ALU_P_INST/alu_nand_out
add wave -noupdate /top_level/ALU_P_INST/rb_irout
add wave -noupdate /top_level/ALU_P_INST/rbimm6out
add wave -noupdate /top_level/ALU_P_INST/alu_p_out_temp
add wave -noupdate /top_level/ALU_P_INST/rb_dest_rrtagout
add wave -noupdate /top_level/ALU_P_INST/rb_carrytagout
add wave -noupdate /top_level/ALU_P_INST/rb_zerotagout
add wave -noupdate /top_level/ALU_P_INST/rb_spectagout
add wave -noupdate /top_level/ALU_P_INST/rbdestr7out
add wave -noupdate /top_level/ALU_P_INST/alu_p_brach_taken_temp
add wave -noupdate /top_level/ALU_P_INST/alu_p_brach_nottaken_temp
add wave -noupdate /top_level/ALU_P_INST/alu_p_valid_out_temp
add wave -noupdate /top_level/ALU_P_INST/rb_validout
add wave -noupdate /top_level/ALU_P_INST/rb_carryout
add wave -noupdate /top_level/ALU_P_INST/rb_zeroout
add wave -noupdate /top_level/ALU_P_INST/rb_carryreadyout
add wave -noupdate /top_level/ALU_P_INST/rb_zeroreadyout
add wave -noupdate /top_level/ALU_P_INST/alu_p_comp
add wave -noupdate /top_level/ALU_P_INST/dependency_special_case_c
add wave -noupdate /top_level/ALU_P_INST/dependency_special_case_z
add wave -noupdate /top_level/ALU_P_INST/dependency_c
add wave -noupdate /top_level/ALU_P_INST/dependency_z
add wave -noupdate /top_level/ALU_P_INST/alu_p_z_temp
add wave -noupdate /top_level/ALU_P_INST/alu_p_c_temp
add wave -noupdate /top_level/ARF_BUSY_INST/Ard_1
add wave -noupdate /top_level/ARF_BUSY_INST/Ard_2
add wave -noupdate /top_level/ARF_BUSY_INST/Ard_3
add wave -noupdate /top_level/ARF_BUSY_INST/Ard_4
add wave -noupdate /top_level/ARF_BUSY_INST/Ard_5
add wave -noupdate /top_level/ARF_BUSY_INST/Ard_6
add wave -noupdate /top_level/ARF_BUSY_INST/Awr_1
add wave -noupdate /top_level/ARF_BUSY_INST/Awr_2
add wave -noupdate /top_level/ARF_BUSY_INST/Awr_3
add wave -noupdate /top_level/ARF_BUSY_INST/Awr_4
add wave -noupdate /top_level/ARF_BUSY_INST/Din_1
add wave -noupdate /top_level/ARF_BUSY_INST/Din_2
add wave -noupdate /top_level/ARF_BUSY_INST/Din_3
add wave -noupdate /top_level/ARF_BUSY_INST/Din_4
add wave -noupdate /top_level/ARF_BUSY_INST/RF_write1
add wave -noupdate /top_level/ARF_BUSY_INST/RF_write2
add wave -noupdate /top_level/ARF_BUSY_INST/RF_write3
add wave -noupdate /top_level/ARF_BUSY_INST/RF_write4
add wave -noupdate /top_level/ARF_BUSY_INST/clk
add wave -noupdate /top_level/ARF_BUSY_INST/clr
add wave -noupdate /top_level/ARF_BUSY_INST/Dout_1
add wave -noupdate /top_level/ARF_BUSY_INST/Dout_2
add wave -noupdate /top_level/ARF_BUSY_INST/Dout_3
add wave -noupdate /top_level/ARF_BUSY_INST/Dout_4
add wave -noupdate /top_level/ARF_BUSY_INST/Dout_5
add wave -noupdate /top_level/ARF_BUSY_INST/Dout_6
add wave -noupdate /top_level/ARF_BUSY_INST/reg_data0
add wave -noupdate /top_level/ARF_BUSY_INST/reg_data1
add wave -noupdate /top_level/ARF_BUSY_INST/reg_data2
add wave -noupdate /top_level/ARF_BUSY_INST/reg_data3
add wave -noupdate /top_level/ARF_BUSY_INST/reg_data4
add wave -noupdate /top_level/ARF_BUSY_INST/reg_data5
add wave -noupdate /top_level/ARF_BUSY_INST/reg_data6
add wave -noupdate /top_level/ARF_BUSY_INST/reg_data7
add wave -noupdate /top_level/ARF_BUSY_INST/Data0
add wave -noupdate /top_level/ARF_BUSY_INST/Data1
add wave -noupdate /top_level/ARF_BUSY_INST/Data2
add wave -noupdate /top_level/ARF_BUSY_INST/Data3
add wave -noupdate /top_level/ARF_BUSY_INST/Data4
add wave -noupdate /top_level/ARF_BUSY_INST/Data5
add wave -noupdate /top_level/ARF_BUSY_INST/Data6
add wave -noupdate /top_level/ARF_BUSY_INST/Data7
add wave -noupdate /top_level/ARF_BUSY_INST/en_vec
add wave -noupdate /top_level/ARF_BUSY_INST/en_vec1
add wave -noupdate /top_level/ARF_BUSY_INST/en_vec2
add wave -noupdate /top_level/ARF_BUSY_INST/en_vec3
add wave -noupdate /top_level/ARF_BUSY_INST/en_vec4
add wave -noupdate /top_level/ARF_BUSY_INST/e
add wave -noupdate /top_level/ARF_INST/data_length
add wave -noupdate /top_level/ARF_INST/Ard_1
add wave -noupdate /top_level/ARF_INST/Ard_2
add wave -noupdate /top_level/ARF_INST/Ard_3
add wave -noupdate /top_level/ARF_INST/Ard_4
add wave -noupdate /top_level/ARF_INST/Awr_1
add wave -noupdate /top_level/ARF_INST/Awr_2
add wave -noupdate /top_level/ARF_INST/Awr_3
add wave -noupdate /top_level/ARF_INST/Din_1
add wave -noupdate /top_level/ARF_INST/Din_2
add wave -noupdate /top_level/ARF_INST/Din_3
add wave -noupdate /top_level/ARF_INST/RF_write1
add wave -noupdate /top_level/ARF_INST/RF_write2
add wave -noupdate /top_level/ARF_INST/RF_write3
add wave -noupdate /top_level/ARF_INST/clk
add wave -noupdate /top_level/ARF_INST/clr
add wave -noupdate /top_level/ARF_INST/Dout_1
add wave -noupdate /top_level/ARF_INST/Dout_2
add wave -noupdate /top_level/ARF_INST/Dout_3
add wave -noupdate /top_level/ARF_INST/Dout_4
add wave -noupdate /top_level/ARF_INST/reg_data0
add wave -noupdate /top_level/ARF_INST/reg_data1
add wave -noupdate /top_level/ARF_INST/reg_data2
add wave -noupdate /top_level/ARF_INST/reg_data3
add wave -noupdate /top_level/ARF_INST/reg_data4
add wave -noupdate /top_level/ARF_INST/reg_data5
add wave -noupdate /top_level/ARF_INST/reg_data6
add wave -noupdate /top_level/ARF_INST/reg_data7
add wave -noupdate /top_level/ARF_INST/Data0
add wave -noupdate /top_level/ARF_INST/Data1
add wave -noupdate /top_level/ARF_INST/Data2
add wave -noupdate /top_level/ARF_INST/Data3
add wave -noupdate /top_level/ARF_INST/Data4
add wave -noupdate /top_level/ARF_INST/Data5
add wave -noupdate /top_level/ARF_INST/Data6
add wave -noupdate /top_level/ARF_INST/Data7
add wave -noupdate /top_level/ARF_INST/en_vec
add wave -noupdate /top_level/ARF_INST/en_vec1a
add wave -noupdate /top_level/ARF_INST/en_vec1
add wave -noupdate /top_level/ARF_INST/en_vec2
add wave -noupdate /top_level/ARF_INST/en_vec3
add wave -noupdate /top_level/ARF_INST/e
add wave -noupdate /top_level/ARF_TAG_INST/data_length
add wave -noupdate /top_level/ARF_TAG_INST/Ard_1
add wave -noupdate /top_level/ARF_TAG_INST/Ard_2
add wave -noupdate /top_level/ARF_TAG_INST/Ard_3
add wave -noupdate /top_level/ARF_TAG_INST/Ard_4
add wave -noupdate /top_level/ARF_TAG_INST/Ard_5
add wave -noupdate /top_level/ARF_TAG_INST/Ard_6
add wave -noupdate /top_level/ARF_TAG_INST/Ard_7
add wave -noupdate /top_level/ARF_TAG_INST/Ard_8
add wave -noupdate /top_level/ARF_TAG_INST/Awr_1
add wave -noupdate /top_level/ARF_TAG_INST/Awr_2
add wave -noupdate /top_level/ARF_TAG_INST/Din_1
add wave -noupdate /top_level/ARF_TAG_INST/Din_2
add wave -noupdate /top_level/ARF_TAG_INST/RF_write1
add wave -noupdate /top_level/ARF_TAG_INST/RF_write2
add wave -noupdate /top_level/ARF_TAG_INST/clk
add wave -noupdate /top_level/ARF_TAG_INST/clr
add wave -noupdate /top_level/ARF_TAG_INST/Dout_1
add wave -noupdate /top_level/ARF_TAG_INST/Dout_2
add wave -noupdate /top_level/ARF_TAG_INST/Dout_3
add wave -noupdate /top_level/ARF_TAG_INST/Dout_4
add wave -noupdate /top_level/ARF_TAG_INST/Dout_5
add wave -noupdate /top_level/ARF_TAG_INST/Dout_6
add wave -noupdate /top_level/ARF_TAG_INST/Dout_7
add wave -noupdate /top_level/ARF_TAG_INST/Dout_8
add wave -noupdate /top_level/ARF_TAG_INST/reg_data0
add wave -noupdate /top_level/ARF_TAG_INST/reg_data1
add wave -noupdate /top_level/ARF_TAG_INST/reg_data2
add wave -noupdate /top_level/ARF_TAG_INST/reg_data3
add wave -noupdate /top_level/ARF_TAG_INST/reg_data4
add wave -noupdate /top_level/ARF_TAG_INST/reg_data5
add wave -noupdate /top_level/ARF_TAG_INST/reg_data6
add wave -noupdate /top_level/ARF_TAG_INST/reg_data7
add wave -noupdate /top_level/ARF_TAG_INST/Data0
add wave -noupdate /top_level/ARF_TAG_INST/Data1
add wave -noupdate /top_level/ARF_TAG_INST/Data2
add wave -noupdate /top_level/ARF_TAG_INST/Data3
add wave -noupdate /top_level/ARF_TAG_INST/Data4
add wave -noupdate /top_level/ARF_TAG_INST/Data5
add wave -noupdate /top_level/ARF_TAG_INST/Data6
add wave -noupdate /top_level/ARF_TAG_INST/Data7
add wave -noupdate /top_level/ARF_TAG_INST/en_vec
add wave -noupdate /top_level/ARF_TAG_INST/en_vec1
add wave -noupdate /top_level/ARF_TAG_INST/en_vec2
add wave -noupdate /top_level/ARF_TAG_INST/e
add wave -noupdate /top_level/CARRY_BUSY_INST/clk
add wave -noupdate /top_level/CARRY_BUSY_INST/wr
add wave -noupdate /top_level/CARRY_BUSY_INST/clr
add wave -noupdate /top_level/CARRY_BUSY_INST/din
add wave -noupdate /top_level/CARRY_BUSY_INST/dout
add wave -noupdate /top_level/CARRY_INST/clk
add wave -noupdate /top_level/CARRY_INST/wr
add wave -noupdate /top_level/CARRY_INST/clr
add wave -noupdate /top_level/CARRY_INST/din
add wave -noupdate /top_level/CARRY_INST/dout
add wave -noupdate /top_level/CARRY_TAG_INST/data_length
add wave -noupdate /top_level/CARRY_TAG_INST/clk
add wave -noupdate /top_level/CARRY_TAG_INST/wr
add wave -noupdate /top_level/CARRY_TAG_INST/clr
add wave -noupdate /top_level/CARRY_TAG_INST/din
add wave -noupdate /top_level/CARRY_TAG_INST/dout
add wave -noupdate /top_level/DRAM_INST/address_wr_1
add wave -noupdate /top_level/DRAM_INST/address_wr_2
add wave -noupdate /top_level/DRAM_INST/address_rd
add wave -noupdate /top_level/DRAM_INST/clock
add wave -noupdate /top_level/DRAM_INST/data_in_1
add wave -noupdate /top_level/DRAM_INST/data_in_2
add wave -noupdate /top_level/DRAM_INST/rden
add wave -noupdate /top_level/DRAM_INST/wren_1
add wave -noupdate /top_level/DRAM_INST/wren_2
add wave -noupdate /top_level/DRAM_INST/read_data_out
add wave -noupdate /top_level/DRAM_INST/RAM
add wave -noupdate /top_level/DRAM_INST/data_1_temp
add wave -noupdate /top_level/ID_INST/clk
add wave -noupdate /top_level/ID_INST/reset
add wave -noupdate /top_level/ID_INST/ra1_val_out
add wave -noupdate /top_level/ID_INST/ra2_val_out
add wave -noupdate /top_level/ID_INST/ra1_pc_out
add wave -noupdate /top_level/ID_INST/ra1_ir_out
add wave -noupdate /top_level/ID_INST/ra2_pc_out
add wave -noupdate /top_level/ID_INST/ra2_ir_out
add wave -noupdate /top_level/ID_INST/free_rrf_vec
add wave -noupdate /top_level/ID_INST/data1
add wave -noupdate /top_level/ID_INST/data2
add wave -noupdate /top_level/ID_INST/data3
add wave -noupdate /top_level/ID_INST/data4
add wave -noupdate /top_level/ID_INST/busy1
add wave -noupdate /top_level/ID_INST/busy2
add wave -noupdate /top_level/ID_INST/busy3
add wave -noupdate /top_level/ID_INST/busy4
add wave -noupdate /top_level/ID_INST/tag1
add wave -noupdate /top_level/ID_INST/tag2
add wave -noupdate /top_level/ID_INST/tag3
add wave -noupdate /top_level/ID_INST/tag4
add wave -noupdate /top_level/ID_INST/C_in
add wave -noupdate /top_level/ID_INST/Z_in
add wave -noupdate /top_level/ID_INST/C_busybit_in
add wave -noupdate /top_level/ID_INST/Z_busybit_in
add wave -noupdate /top_level/ID_INST/busy_dest1_in
add wave -noupdate /top_level/ID_INST/busy_dest2_in
add wave -noupdate /top_level/ID_INST/C_tag_in
add wave -noupdate /top_level/ID_INST/Z_tag_in
add wave -noupdate /top_level/ID_INST/tag_dest1_in
add wave -noupdate /top_level/ID_INST/tag_dest2_in
add wave -noupdate /top_level/ID_INST/taken_branch_detected
add wave -noupdate /top_level/ID_INST/not_taken_branch_detected
add wave -noupdate /top_level/ID_INST/spec_tag_rb_in
add wave -noupdate /top_level/ID_INST/rs_full_in
add wave -noupdate /top_level/ID_INST/lm_stall_in
add wave -noupdate /top_level/ID_INST/lw_r7_resolved
add wave -noupdate /top_level/ID_INST/alu_r7_resolved
add wave -noupdate /top_level/ID_INST/jlr_resolved
add wave -noupdate /top_level/ID_INST/store_retirement_count
add wave -noupdate /top_level/ID_INST/free_rrf_vec_out
add wave -noupdate /top_level/ID_INST/Ard1a
add wave -noupdate /top_level/ID_INST/Ard1b
add wave -noupdate /top_level/ID_INST/Ard2a
add wave -noupdate /top_level/ID_INST/Ard2b
add wave -noupdate /top_level/ID_INST/Ard1c
add wave -noupdate /top_level/ID_INST/Ard2c
add wave -noupdate /top_level/ID_INST/Awr1
add wave -noupdate /top_level/ID_INST/Awr2
add wave -noupdate /top_level/ID_INST/pc1
add wave -noupdate /top_level/ID_INST/pc2
add wave -noupdate /top_level/ID_INST/ir1
add wave -noupdate /top_level/ID_INST/ir2
add wave -noupdate /top_level/ID_INST/x1_op1
add wave -noupdate /top_level/ID_INST/x1_op2
add wave -noupdate /top_level/ID_INST/x2_op1
add wave -noupdate /top_level/ID_INST/x2_op2
add wave -noupdate /top_level/ID_INST/x1_op1_ready
add wave -noupdate /top_level/ID_INST/x1_op2_ready
add wave -noupdate /top_level/ID_INST/x2_op1_ready
add wave -noupdate /top_level/ID_INST/x2_op2_ready
add wave -noupdate /top_level/ID_INST/x1_val
add wave -noupdate /top_level/ID_INST/x2_val
add wave -noupdate /top_level/ID_INST/C_out
add wave -noupdate /top_level/ID_INST/Z_out
add wave -noupdate /top_level/ID_INST/C_ready
add wave -noupdate /top_level/ID_INST/Z_ready
add wave -noupdate /top_level/ID_INST/C_wr
add wave -noupdate /top_level/ID_INST/Z_wr
add wave -noupdate /top_level/ID_INST/C_2_out
add wave -noupdate /top_level/ID_INST/C_2_ready
add wave -noupdate /top_level/ID_INST/C_2_wr
add wave -noupdate /top_level/ID_INST/Z_2_out
add wave -noupdate /top_level/ID_INST/Z_2_ready
add wave -noupdate /top_level/ID_INST/Z_2_wr
add wave -noupdate /top_level/ID_INST/spec_tag_rs_out1
add wave -noupdate /top_level/ID_INST/spec_tag_rs_out2
add wave -noupdate /top_level/ID_INST/store_tag_rs_out1
add wave -noupdate /top_level/ID_INST/store_tag_rs_out2
add wave -noupdate /top_level/ID_INST/C_busybit_out
add wave -noupdate /top_level/ID_INST/Z_busybit_out
add wave -noupdate /top_level/ID_INST/C_2_busybit_out
add wave -noupdate /top_level/ID_INST/Z_2_busybit_out
add wave -noupdate /top_level/ID_INST/C_tag_out_arf
add wave -noupdate /top_level/ID_INST/Z_tag_out_arf
add wave -noupdate /top_level/ID_INST/C_2_tag_out_arf
add wave -noupdate /top_level/ID_INST/Z_2_tag_out_arf
add wave -noupdate /top_level/ID_INST/busy_dest1_out
add wave -noupdate /top_level/ID_INST/busy_dest2_out
add wave -noupdate /top_level/ID_INST/dest_AR_tag_out
add wave -noupdate /top_level/ID_INST/dest_AR_tag_2_out
add wave -noupdate /top_level/ID_INST/C_tag_out_rs
add wave -noupdate /top_level/ID_INST/Z_tag_out_rs
add wave -noupdate /top_level/ID_INST/C_2_tag_out_rs
add wave -noupdate /top_level/ID_INST/Z_2_tag_out_rs
add wave -noupdate /top_level/ID_INST/ra1_invalidate_out
add wave -noupdate /top_level/ID_INST/ra2_invalidate_out
add wave -noupdate /top_level/ID_INST/pc_en_out
add wave -noupdate /top_level/ID_INST/ra_en_out
add wave -noupdate /top_level/ID_INST/arf_busy_wr_en1
add wave -noupdate /top_level/ID_INST/arf_busy_wr_en2
add wave -noupdate /top_level/ID_INST/arf_tag_wr_en1
add wave -noupdate /top_level/ID_INST/arf_tag_wr_en2
add wave -noupdate /top_level/ID_INST/adder2_out
add wave -noupdate /top_level/ID_INST/adder3_out
add wave -noupdate /top_level/ID_INST/ZA7_1_out
add wave -noupdate /top_level/ID_INST/ZA7_2_out
add wave -noupdate /top_level/ID_INST/S0
add wave -noupdate /top_level/ID_INST/S1
add wave -noupdate /top_level/ID_INST/S2
add wave -noupdate /top_level/ID_INST/S3
add wave -noupdate /top_level/ID_INST/x1_add
add wave -noupdate /top_level/ID_INST/x1_adc
add wave -noupdate /top_level/ID_INST/x1_adz
add wave -noupdate /top_level/ID_INST/x1_adi
add wave -noupdate /top_level/ID_INST/x1_ndu
add wave -noupdate /top_level/ID_INST/x1_ndc
add wave -noupdate /top_level/ID_INST/x1_ndz
add wave -noupdate /top_level/ID_INST/x1_lhi
add wave -noupdate /top_level/ID_INST/x1_lw
add wave -noupdate /top_level/ID_INST/x1_sw
add wave -noupdate /top_level/ID_INST/x1_lm
add wave -noupdate /top_level/ID_INST/x1_sm
add wave -noupdate /top_level/ID_INST/x1_beq
add wave -noupdate /top_level/ID_INST/x1_jal
add wave -noupdate /top_level/ID_INST/x1_jlr
add wave -noupdate /top_level/ID_INST/x2_add
add wave -noupdate /top_level/ID_INST/x2_adc
add wave -noupdate /top_level/ID_INST/x2_adz
add wave -noupdate /top_level/ID_INST/x2_adi
add wave -noupdate /top_level/ID_INST/x2_ndu
add wave -noupdate /top_level/ID_INST/x2_ndc
add wave -noupdate /top_level/ID_INST/x2_ndz
add wave -noupdate /top_level/ID_INST/x2_lhi
add wave -noupdate /top_level/ID_INST/x2_lw
add wave -noupdate /top_level/ID_INST/x2_sw
add wave -noupdate /top_level/ID_INST/x2_lm
add wave -noupdate /top_level/ID_INST/x2_sm
add wave -noupdate /top_level/ID_INST/x2_beq
add wave -noupdate /top_level/ID_INST/x2_jal
add wave -noupdate /top_level/ID_INST/x2_jlr
add wave -noupdate /top_level/ID_INST/twoRRnotFree
add wave -noupdate /top_level/ID_INST/penout2
add wave -noupdate /top_level/ID_INST/penout1
add wave -noupdate /top_level/ID_INST/SE_Ra1_imm9
add wave -noupdate /top_level/ID_INST/SE_Ra2_imm9
add wave -noupdate /top_level/ID_INST/c_adder2out
add wave -noupdate /top_level/ID_INST/c_adder3out
add wave -noupdate /top_level/ID_INST/spec_tag_reg_en
add wave -noupdate /top_level/ID_INST/store_tag_reg_en
add wave -noupdate /top_level/ID_INST/spec_tag_reg_in
add wave -noupdate /top_level/ID_INST/spec_tag_reg_out
add wave -noupdate /top_level/ID_INST/store_tag_reg_in
add wave -noupdate /top_level/ID_INST/store_tag_reg_out
add wave -noupdate /top_level/ID_INST/store_tag_reg_out_minus_one
add wave -noupdate /top_level/ID_INST/store_tag_reg_out_plus_one
add wave -noupdate /top_level/ID_INST/store_tag_reg_out_minus_two
add wave -noupdate /top_level/ID_INST/store_tag_reg_out_plus_two
add wave -noupdate /top_level/ID_INST/SE_store_tag_reg_out
add wave -noupdate /top_level/ID_INST/c_store_tag1
add wave -noupdate /top_level/ID_INST/c_store_tag2
add wave -noupdate /top_level/ID_INST/c_store_tag3
add wave -noupdate /top_level/ID_INST/c_store_tag4
add wave -noupdate /top_level/ID_INST/free_rrf_vec_out_sig
add wave -noupdate /top_level/ID_INST/free_rrf_vec_out_sig2
add wave -noupdate /top_level/IFETCH_INST/data_length16
add wave -noupdate /top_level/IFETCH_INST/clk
add wave -noupdate /top_level/IFETCH_INST/reset
add wave -noupdate /top_level/IFETCH_INST/reset_bar
add wave -noupdate /top_level/IFETCH_INST/S0
add wave -noupdate /top_level/IFETCH_INST/S1
add wave -noupdate /top_level/IFETCH_INST/S2
add wave -noupdate /top_level/IFETCH_INST/S3
add wave -noupdate /top_level/IFETCH_INST/pc_en
add wave -noupdate /top_level/IFETCH_INST/ra1_invalidate
add wave -noupdate /top_level/IFETCH_INST/ra2_invalidate
add wave -noupdate /top_level/IFETCH_INST/ra_en
add wave -noupdate /top_level/IFETCH_INST/adder2_out
add wave -noupdate /top_level/IFETCH_INST/adder3_out
add wave -noupdate /top_level/IFETCH_INST/rb_op2
add wave -noupdate /top_level/IFETCH_INST/adder4_out
add wave -noupdate /top_level/IFETCH_INST/alu1_out
add wave -noupdate /top_level/IFETCH_INST/ZA7_1_out
add wave -noupdate /top_level/IFETCH_INST/ZA7_2_out
add wave -noupdate /top_level/IFETCH_INST/dmem_dout
add wave -noupdate /top_level/IFETCH_INST/ra1_val_out
add wave -noupdate /top_level/IFETCH_INST/ra2_val_out
add wave -noupdate /top_level/IFETCH_INST/ra1_pc_out
add wave -noupdate /top_level/IFETCH_INST/ra1_ir_out
add wave -noupdate /top_level/IFETCH_INST/ra2_pc_out
add wave -noupdate /top_level/IFETCH_INST/ra2_ir_out
add wave -noupdate /top_level/IFETCH_INST/pc_out
add wave -noupdate /top_level/IFETCH_INST/temp_pc
add wave -noupdate /top_level/IFETCH_INST/adder1_out
add wave -noupdate /top_level/IFETCH_INST/pc_in_plus1
add wave -noupdate /top_level/IFETCH_INST/imem_dout1
add wave -noupdate /top_level/IFETCH_INST/imem_dout2
add wave -noupdate /top_level/IFETCH_INST/pc_in
add wave -noupdate /top_level/IFETCH_INST/ra1_val_in
add wave -noupdate /top_level/IFETCH_INST/ra2_val_in
add wave -noupdate /top_level/LS_P_INST/clk
add wave -noupdate /top_level/LS_P_INST/reset
add wave -noupdate /top_level/LS_P_INST/rc_pc
add wave -noupdate /top_level/LS_P_INST/rc_op1
add wave -noupdate /top_level/LS_P_INST/rc_op2
add wave -noupdate /top_level/LS_P_INST/rc_ir
add wave -noupdate /top_level/LS_P_INST/read_datafrommem
add wave -noupdate /top_level/LS_P_INST/rc_dest_rrtag
add wave -noupdate /top_level/LS_P_INST/rc_carrytag
add wave -noupdate /top_level/LS_P_INST/rc_zerotag
add wave -noupdate /top_level/LS_P_INST/rc_spectag
add wave -noupdate /top_level/LS_P_INST/rc_valid
add wave -noupdate /top_level/LS_P_INST/rc_carry
add wave -noupdate /top_level/LS_P_INST/rc_carryready
add wave -noupdate /top_level/LS_P_INST/rc_zero
add wave -noupdate /top_level/LS_P_INST/rc_zeroready
add wave -noupdate /top_level/LS_P_INST/rrf_valid_vect_in
add wave -noupdate /top_level/LS_P_INST/ls_p_data_out
add wave -noupdate /top_level/LS_P_INST/read_addr
add wave -noupdate /top_level/LS_P_INST/write_addr
add wave -noupdate /top_level/LS_P_INST/rrf_tag_out
add wave -noupdate /top_level/LS_P_INST/rrf_valid_vect_ls_p_out
add wave -noupdate /top_level/LS_P_INST/mem_read_en
add wave -noupdate /top_level/LS_P_INST/mem_write_en
add wave -noupdate /top_level/LS_P_INST/lw_r7_resolved
add wave -noupdate /top_level/LS_P_INST/ls_p_z
add wave -noupdate /top_level/LS_P_INST/rrf_en_out
add wave -noupdate /top_level/LS_P_INST/ls_p_val_out
add wave -noupdate /top_level/LS_P_INST/ls_p_pc_out
add wave -noupdate /top_level/LS_P_INST/rc_pcout
add wave -noupdate /top_level/LS_P_INST/rc_op1out
add wave -noupdate /top_level/LS_P_INST/rc_op2out
add wave -noupdate /top_level/LS_P_INST/add_in_a
add wave -noupdate /top_level/LS_P_INST/add_in_b
add wave -noupdate /top_level/LS_P_INST/add_out
add wave -noupdate /top_level/LS_P_INST/rc_irout
add wave -noupdate /top_level/LS_P_INST/rcimm6out
add wave -noupdate /top_level/LS_P_INST/rcimm9out
add wave -noupdate /top_level/LS_P_INST/ls_p_data_out_temp
add wave -noupdate /top_level/LS_P_INST/rc_dest_rrtagout
add wave -noupdate /top_level/LS_P_INST/rc_carrytagout
add wave -noupdate /top_level/LS_P_INST/rc_zerotagout
add wave -noupdate /top_level/LS_P_INST/rc_spectagout
add wave -noupdate /top_level/LS_P_INST/alu_p_brach_taken_temp
add wave -noupdate /top_level/LS_P_INST/rc_validout
add wave -noupdate /top_level/LS_P_INST/rc_carryout
add wave -noupdate /top_level/LS_P_INST/rc_zeroout
add wave -noupdate /top_level/LS_P_INST/rc_carryreadyout
add wave -noupdate /top_level/LS_P_INST/rc_zeroreadyout
add wave -noupdate /top_level/LS_P_INST/unused_c
add wave -noupdate /top_level/LS_P_INST/ls_p_z_temp
add wave -noupdate /top_level/ROB_INST/clk
add wave -noupdate /top_level/ROB_INST/reset
add wave -noupdate /top_level/ROB_INST/pc_1_in
add wave -noupdate /top_level/ROB_INST/pc_2_in
add wave -noupdate /top_level/ROB_INST/dest_1_in
add wave -noupdate /top_level/ROB_INST/dest_2_in
add wave -noupdate /top_level/ROB_INST/ir_1_in
add wave -noupdate /top_level/ROB_INST/ir_2_in
add wave -noupdate /top_level/ROB_INST/pc_exec_1_in
add wave -noupdate /top_level/ROB_INST/pc_exec_2_in
add wave -noupdate /top_level/ROB_INST/dest_tag_1_in
add wave -noupdate /top_level/ROB_INST/dest_tag_2_in
add wave -noupdate /top_level/ROB_INST/c_tag_1_in
add wave -noupdate /top_level/ROB_INST/c_tag_2_in
add wave -noupdate /top_level/ROB_INST/z_tag_1_in
add wave -noupdate /top_level/ROB_INST/z_tag_2_in
add wave -noupdate /top_level/ROB_INST/valid_1_in
add wave -noupdate /top_level/ROB_INST/valid_2_in
add wave -noupdate /top_level/ROB_INST/complete_exec_1_in
add wave -noupdate /top_level/ROB_INST/complete_exec_2_in
add wave -noupdate /top_level/ROB_INST/mr_1_in
add wave -noupdate /top_level/ROB_INST/mr_2_in
add wave -noupdate /top_level/ROB_INST/c_1_in
add wave -noupdate /top_level/ROB_INST/c_2_in
add wave -noupdate /top_level/ROB_INST/z_1_in
add wave -noupdate /top_level/ROB_INST/z_2_in
add wave -noupdate /top_level/ROB_INST/cwr_1_in
add wave -noupdate /top_level/ROB_INST/cwr_2_in
add wave -noupdate /top_level/ROB_INST/zwr_1_in
add wave -noupdate /top_level/ROB_INST/zwr_2_in
add wave -noupdate /top_level/ROB_INST/alu_p_in
add wave -noupdate /top_level/ROB_INST/ls_p_write_addr
add wave -noupdate /top_level/ROB_INST/ls_p_data
add wave -noupdate /top_level/ROB_INST/valid_exec_alu
add wave -noupdate /top_level/ROB_INST/valid_exec_ls
add wave -noupdate /top_level/ROB_INST/alu_c_in
add wave -noupdate /top_level/ROB_INST/alu_z_in
add wave -noupdate /top_level/ROB_INST/ls_z_in
add wave -noupdate /top_level/ROB_INST/alu_p_no_ans
add wave -noupdate /top_level/ROB_INST/free_rrf_vect_in
add wave -noupdate /top_level/ROB_INST/val_rrf_vect_in
add wave -noupdate /top_level/ROB_INST/arf_tag_in_1
add wave -noupdate /top_level/ROB_INST/arf_tag_in_2
add wave -noupdate /top_level/ROB_INST/c_tag_in
add wave -noupdate /top_level/ROB_INST/z_tag_in
add wave -noupdate /top_level/ROB_INST/robfull
add wave -noupdate /top_level/ROB_INST/finalc_out
add wave -noupdate /top_level/ROB_INST/finalz_out
add wave -noupdate /top_level/ROB_INST/data_out_1
add wave -noupdate /top_level/ROB_INST/data_out_2
add wave -noupdate /top_level/ROB_INST/data_out_3
add wave -noupdate /top_level/ROB_INST/mem_addr_1
add wave -noupdate /top_level/ROB_INST/mem_addr_2
add wave -noupdate /top_level/ROB_INST/arf_addr_out_1
add wave -noupdate /top_level/ROB_INST/arf_addr_out_2
add wave -noupdate /top_level/ROB_INST/rrf_addr_out_1
add wave -noupdate /top_level/ROB_INST/rrf_addr_out_2
add wave -noupdate /top_level/ROB_INST/no_of_stores_cleared
add wave -noupdate /top_level/ROB_INST/free_rrf_vect_out
add wave -noupdate /top_level/ROB_INST/val_rrf_vect_out
add wave -noupdate /top_level/ROB_INST/arf_en_1
add wave -noupdate /top_level/ROB_INST/arf_en_2
add wave -noupdate /top_level/ROB_INST/arf_en_3
add wave -noupdate /top_level/ROB_INST/mem_en_1
add wave -noupdate /top_level/ROB_INST/mem_en_2
add wave -noupdate /top_level/ROB_INST/c_en
add wave -noupdate /top_level/ROB_INST/z_en
add wave -noupdate /top_level/ROB_INST/arf_busy_en_1
add wave -noupdate /top_level/ROB_INST/arf_busy_en_2
add wave -noupdate /top_level/ROB_INST/z_busy_en
add wave -noupdate /top_level/ROB_INST/c_busy_en
add wave -noupdate /top_level/ROB_INST/pc
add wave -noupdate /top_level/ROB_INST/dest
add wave -noupdate /top_level/ROB_INST/ir
add wave -noupdate /top_level/ROB_INST/result
add wave -noupdate /top_level/ROB_INST/pc_exec
add wave -noupdate /top_level/ROB_INST/pc_out
add wave -noupdate /top_level/ROB_INST/dest_out
add wave -noupdate /top_level/ROB_INST/ir_out
add wave -noupdate /top_level/ROB_INST/result_out
add wave -noupdate /top_level/ROB_INST/pc_exec_out
add wave -noupdate /top_level/ROB_INST/dest_tag_out
add wave -noupdate /top_level/ROB_INST/dest_tag
add wave -noupdate /top_level/ROB_INST/c_tag_out
add wave -noupdate /top_level/ROB_INST/z_tag_out
add wave -noupdate /top_level/ROB_INST/c_tag
add wave -noupdate /top_level/ROB_INST/z_tag
add wave -noupdate /top_level/ROB_INST/en
add wave -noupdate /top_level/ROB_INST/valid
add wave -noupdate /top_level/ROB_INST/complete_exec
add wave -noupdate /top_level/ROB_INST/mr
add wave -noupdate /top_level/ROB_INST/c
add wave -noupdate /top_level/ROB_INST/z
add wave -noupdate /top_level/ROB_INST/cwr
add wave -noupdate /top_level/ROB_INST/zwr
add wave -noupdate /top_level/ROB_INST/valid_out
add wave -noupdate /top_level/ROB_INST/complete_exec_out
add wave -noupdate /top_level/ROB_INST/mr_out
add wave -noupdate /top_level/ROB_INST/c_out
add wave -noupdate /top_level/ROB_INST/z_out
add wave -noupdate /top_level/ROB_INST/cwr_out
add wave -noupdate /top_level/ROB_INST/zwr_out
add wave -noupdate /top_level/ROB_INST/no_wb
add wave -noupdate /top_level/ROB_INST/no_wb_out
add wave -noupdate /top_level/ROB_INST/tail_ptr
add wave -noupdate /top_level/ROB_INST/head_ptr
add wave -noupdate /top_level/ROB_INST/tail_ptr_out
add wave -noupdate /top_level/ROB_INST/head_ptr_out
add wave -noupdate /top_level/ROB_INST/tail_ptr_out_plus1
add wave -noupdate /top_level/ROB_INST/head_ptr_out_plus1
add wave -noupdate /top_level/ROB_INST/tail_ptr_out_plus2
add wave -noupdate /top_level/ROB_INST/head_ptr_out_plus2
add wave -noupdate /top_level/ROB_INST/mr1
add wave -noupdate /top_level/ROB_INST/mr2
add wave -noupdate /top_level/ROB_INST/c_en_temp
add wave -noupdate /top_level/ROB_INST/z_en_temp
add wave -noupdate /top_level/ROB_INST/mem_en_1_temp
add wave -noupdate /top_level/ROB_INST/mem_en_2_temp
add wave -noupdate /top_level/ROB_INST/arf_en_1_temp
add wave -noupdate /top_level/ROB_INST/arf_en_2_temp
add wave -noupdate /top_level/ROB_INST/exec_ptr_1
add wave -noupdate /top_level/ROB_INST/exec_ptr_2
add wave -noupdate /top_level/ROB_INST/dest1
add wave -noupdate /top_level/ROB_INST/dest2
add wave -noupdate /top_level/RS_RRF_SCHED_INST/clk
add wave -noupdate /top_level/RS_RRF_SCHED_INST/reset
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_Awr1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_Awr2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_write1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_write2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_Data1_EX_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_Data2_EX_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_free_vec_ID_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_free_vec_Rob_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_valid_vec_EX_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_valid_vec_Rob_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_free_vec_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_valid_vec_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_pc1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_pc2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_ir1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_ir2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_dest_rr_tag1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_dest_rr_tag2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_carry_tag1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_carry_tag2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_zero_tag1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_zero_tag2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/store_retirement_count
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_op1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_op2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_op1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_op2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_store_tag_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_store_tag_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_zero_ready_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_zero_ready_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_zero_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_zero_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_carry_ready_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_carry_ready_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_carry_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_carry_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_val_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_val_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_op1_val_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_1_op2_val_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_op1_val_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/id_2_op2_val_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/twoRSnotFree_rs
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rb_pc
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rb_op1
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rb_op2
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rb_ir
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rb_dest_rrtag
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rb_valid
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rb_carry
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rb_zero
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rc_pc
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rc_op1
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rc_op2
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rc_ir
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rc_dest_rrtag
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rc_valid
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rc_carry
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rc_zero
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_P_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_P_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_busy_reg_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_busy_reg_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_valid_reg_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rrf_valid_reg_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/en_for_P
add wave -noupdate /top_level/RS_RRF_SCHED_INST/en_for_busy
add wave -noupdate /top_level/RS_RRF_SCHED_INST/en_for_valid
add wave -noupdate /top_level/RS_RRF_SCHED_INST/en_vec1
add wave -noupdate /top_level/RS_RRF_SCHED_INST/en_vec2
add wave -noupdate /top_level/RS_RRF_SCHED_INST/sign_extended_store_tag_minus2
add wave -noupdate /top_level/RS_RRF_SCHED_INST/sign_extended_store_tag_minus1
add wave -noupdate /top_level/RS_RRF_SCHED_INST/sign_extended_store_tag
add wave -noupdate /top_level/RS_RRF_SCHED_INST/pc_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/pc_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op1_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op1_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op2_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op2_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_ir_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_ir_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/store_tag_minus2_carry
add wave -noupdate /top_level/RS_RRF_SCHED_INST/store_tag_minus1_carry
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_zero_ready_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_zero_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_carry_ready_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_carry_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_inst_val_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op2_val_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op1_val_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_zero_ready_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_zero_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_carry_ready_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_carry_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_inst_val_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op2_val_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op1_val_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/pc_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op1_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op2_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_ir_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op1_val_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_op2_val_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_inst_val_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_carry_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_carry_ready_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_zero_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_zero_ready_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_dest_rr_tag_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_carry_tag_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_zero_tag_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_store_tag_en
add wave -noupdate /top_level/RS_RRF_SCHED_INST/store_tag_minus1
add wave -noupdate /top_level/RS_RRF_SCHED_INST/store_tag_minus2
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_store_tag_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_zero_tag_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_carry_tag_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_dest_rr_tag_out
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_dest_rr_tag_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_carry_tag_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_zero_tag_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_store_tag_in
add wave -noupdate /top_level/RS_RRF_SCHED_INST/pennext_twoallotted_rs
add wave -noupdate /top_level/RS_RRF_SCHED_INST/pennext_oneallotted_rs
add wave -noupdate /top_level/RS_RRF_SCHED_INST/penout1_rs_val
add wave -noupdate /top_level/RS_RRF_SCHED_INST/penout2_rs_val
add wave -noupdate /top_level/RS_RRF_SCHED_INST/rs_inst_val_out_vector
add wave -noupdate /top_level/RS_RRF_SCHED_INST/inst_scheduled
add wave -noupdate /top_level/RS_RRF_SCHED_INST/twoRSnotFree_rs_signal
add wave -noupdate /top_level/RS_RRF_SCHED_INST/alu_schedulable_vec
add wave -noupdate /top_level/RS_RRF_SCHED_INST/ls_schedulable_vec
add wave -noupdate /top_level/RS_RRF_SCHED_INST/pennext_alu_sched
add wave -noupdate /top_level/RS_RRF_SCHED_INST/pennext_ls_sched
add wave -noupdate /top_level/RS_RRF_SCHED_INST/no1found_alu_sched
add wave -noupdate /top_level/RS_RRF_SCHED_INST/no1found_ls_sched
add wave -noupdate /top_level/RS_RRF_SCHED_INST/penout_alu_sched
add wave -noupdate /top_level/RS_RRF_SCHED_INST/penout_ls_sched
add wave -noupdate /top_level/ZERO_BUSY_INST/clk
add wave -noupdate /top_level/ZERO_BUSY_INST/wr
add wave -noupdate /top_level/ZERO_BUSY_INST/clr
add wave -noupdate /top_level/ZERO_BUSY_INST/din
add wave -noupdate /top_level/ZERO_BUSY_INST/dout
add wave -noupdate /top_level/ZERO_INST/clk
add wave -noupdate /top_level/ZERO_INST/wr
add wave -noupdate /top_level/ZERO_INST/clr
add wave -noupdate /top_level/ZERO_INST/din
add wave -noupdate /top_level/ZERO_INST/dout
add wave -noupdate /top_level/ZERO_TAG_INST/data_length
add wave -noupdate /top_level/ZERO_TAG_INST/clk
add wave -noupdate /top_level/ZERO_TAG_INST/wr
add wave -noupdate /top_level/ZERO_TAG_INST/clr
add wave -noupdate /top_level/ZERO_TAG_INST/din
add wave -noupdate /top_level/ZERO_TAG_INST/dout
TreeUpdate [SetDefaultTree]
quietly WaveActivateNextPane
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 536
configure wave -valuecolwidth 208
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {545 ps}
